### ISSUE TITLE
. on error

### ISSUE THREAD

**Issue by malaxmimdkm** [KhushrajRathod/pQueue#9]
![Screenshot_1](https://user-images.githubusercontent.com/87426367/129871601-c4dcbb06-3f2f-42b9-917e-aa0712b20168.png)

**Comment by khrj** [comment]
Please take a look at the documentation for this module: https://doc.deno.land/https/deno.land/x/p_queue@1.0.1/mod.ts
And for EventTarget: https://doc.deno.land/builtin/stable#EventTarget

You're looking for `.addEventListener()` instead of `.on()`
